import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ThemeRegistry from "@/styles/theme";
import Providers from "@/store/Providers";
import { SnackbarProvider } from "notistack";
import { SnackbarUtilsConfigurator } from "@/content/snackbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Providers>
        <SnackbarProvider
          maxSnack={6}
          anchorOrigin={{
            vertical: "bottom",
            horizontal: "right",
          }}
          // action={(key) => <SnackbarCloseButton key={key} />}
        >
          <SnackbarUtilsConfigurator />
          <ThemeRegistry>
            <body className={inter.className}>{children}</body>
          </ThemeRegistry>
        </SnackbarProvider>
      </Providers>
    </html>
  );
}
