import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ThemeRegistry from "@/styles/theme";
import Providers from "@/store/Providers";
import { SnackbarProvider } from "notistack";
import { SnackbarUtilsConfigurator } from "@/content/snackbar";
import SnackbarProviders from "@/content/snackbarProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Providers>
        <SnackbarProviders>
          <ThemeRegistry>
            <body className={inter.className}>{children}</body>
          </ThemeRegistry>
        </SnackbarProviders>
      </Providers>
    </html>
  );
}
